version: '3.8'

services:
  inn-tg-bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Production}
      - DOTNET_ENVIRONMENT=${DOTNET_ENVIRONMENT:-Production}
      - Telegram__Token=${TELEGRAM_BOT_TOKEN}
      - Dadata__Token=${DADATA_API_TOKEN}
      - PORT=8080
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 1m
      timeout: 3s
      retries: 3
      start_period: 10s