version: '3.8'

services:
  inn-tg-bot:
    build: .
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - Telegram__Token=${TELEGRAM_BOT_TOKEN}
      - Dadata__Token=${DADATA_API_TOKEN}
      - DOTNET_ENVIRONMENT=${DOTNET_ENVIRONMENT}
    restart: unless-stopped